### ISSUE TITLE
VimeoVanisher does not work together with EmbeddedVideoVanisher (PHP 8)

### ISSUE THREAD

**Issue by josarnold** [backdrop-contrib/gdpr_cookies#50]
The problem are the paths.The vimeo-path of the video is not generated properly and so no video can be displayed.  

**Steps to reproduce:**
1. Use the video_embed_field module to insert a Vimeo-Video via a field
2. Add a Vimeo-URL like https://vimeo.com/123456789
3. Enable VimeoVanisher and EmbeddedVideoVanisher in the gdpr_cookies module

**Expected result:**
The video resources should be loaded if allowed by the user.

**Current result:**
The video is not loadable because the vimeo-path is broken – actually the Video-ID is the problem.

**Cause:** 
The URL is run through RegEx, and then put together again for the embedding, but the particular parts of the path are not calculated and combined together reliable in these two files. The result is an empty or incomplete url-path.  

**Files:** gdpr_cookies/src/Service/VimeoVanisher.php and gdpr_cookies/src/Service/EmbeddedVideoVanisher.php

**My solution:**

I changed line 18 in the VimeoVanisher.php from
`const VIMEO_VIDEO_ID_REGEX = '~^https?:\/\/(?:www\.|player\.)?vimeo.com\/(?:channels\/(?:\w+\/)?|groups\/([^\/]*)\/videos\/|album\/(\d+)\/video\/|video\/|)(\d+)(?:$|\/|\?)(?:[?]?.*)$~i';`

to
`const VIMEO_VIDEO_ID_REGEX = '~https?:\/\/(?:www\.|player\.)?vimeo\.com\/(?:video\/)?(?<id>\d+)(?:$|[\/?])~i';`

and line 45 to 57 in the EmbeddedVideoVanisher.php from 
```
  protected function getVideoData($markup) {
    $data = array();
    $matches = array();

    $ret = preg_match_all(ThirdPartyServicesVanisher::FIND_MARKUP_ATTRIBUTES_REGEX, $markup, $matches);
    if ($ret !== FALSE && $ret > 0) {
      $data = array_combine($matches[1], $matches[4]);

      unset($data['iframe']);
    }

    return $data;
  }
```
to 
```
protected function getVideoData($markup) {
  $data = array();
  $matches = array();

  $ret = preg_match_all(ThirdPartyServicesVanisher::FIND_MARKUP_ATTRIBUTES_REGEX, $markup, $matches);
  if ($ret !== FALSE && $ret > 0) {
    $data = array_combine($matches[1], $matches[4]);

    unset($data['iframe']);

    // Add https: if src only with //
    if (!empty($data['src']) && strpos($data['src'], '//') === 0) {
      $data['src'] = 'https:' . $data['src'];
    }

    // Set default values
    if (!isset($data['width'])) {
      $data['width'] = '640';
    }
    if (!isset($data['height'])) {
      $data['height'] = '360';
    }
  }

  return $data;
}
```

That does the trick.

**Comment by olafgrabienski** [comment]
Interesting, I've also had problems with Vimeo and fixed them by patching _Video Embed Field_. Pointing to related issues for reference:

- https://github.com/backdrop-contrib/gdpr_cookies/issues/22
- https://github.com/backdrop-contrib/video_embed_field/issues/12

**Comment by josarnold** [comment]
@olafgrabienski – I thought it was a domain-level privacy control issue first too but it's the VIMEO_VIDEO_ID_REGEX in VimeoVanisher.php that causes the problem using the video_embed_field module together with gdpr_cookies. The additional changes in the EmbeddedVideoVanisher.php were helpful for me but the main reason, that the videos did not work was the path construction.

**Comment by yorkshire-pudding** [comment]
Thanks for reporting @josarnold and thanks for input @olafgrabienski .  Unfortunately I won't be able to look at this straight away; I've spent quite of time on this module recently (more than I expected when I took it on just over a month ago) and have to prioritise the work that pays the bills.  If people want to prepare a PR and do testing, that will make me reviewing it easier, and more likely it will get merged sooner rather than later.

**Comment by olafgrabienski** [comment]
@josarnold Thanks for your PRs. Are #54 and #55 different approaches to fix the same issue?

**Comment by josarnold** [comment]
@olafgrabienski With #54 I solved the problem with the vimeo-paths. #55 is just an idea to implement vimeo-videos better in that particular case. Please test my solution, if You can. It is very simple and should work for most of the users – but I eliminated all special cases in the Vimeo-URLs and maybe there are still some when that does not function the expected way. I'm just a site builder and I hope, you programming  PROs  know what would be to do if I did something not suitable. I love Backdrop and just want to help a little bit. :-)

**Comment by olafgrabienski** [comment]
@josarnold – I've applied the PR #54 to my testing site, unfortunately with no luck. The video still is still not displayed, and I see the following PHP notice in DBlog:

> Undefined offset: 3 in Backdrop\gdpr_cookies\Service\VimeoVanisher->extractVideoId() (line 64 of /(...)/modules/gdpr_cookies/includes/Service/VimeoVanisher.php).

(PHP version of the testing site is 7.4.33.)

Interestingly, when I apply the PR without the regex changes in the file `VimeoVanisher.php`, the video is displayed, and the PHP notice disappears.

PS: I'm not a programming pro, rather a site architect.

**Comment by josarnold** [comment]
@olafgrabienski I've been struggling with that so long, that I may be wrong about the solution I found through T&E. I tested it the other way around and changed only #55 (EmbeddedVideoVanisher.php) and that suddenly worked. – I don't know.

**Comment by olafgrabienski** [comment]
@josarnold I see! Then I'd like to test PR #55 as well. To be sure what's supposed to work now: Does PR 55 in the current state work for you, or are only the parts in `EmbeddedVideoVanisher.php` relevant?

**Comment by yorkshire-pudding** [comment]
@josarnold 
I can't promise anything but if you could post a list of all the Vimeo URL formats that should be supported, it may be that if it is a case of getting the regex right I can help.

If you fancy another attempt yourself, then I recommend using https://regex101.com/ as a great way to test and troubleshoot regex
If you do revisit your PR, please put:

```
Fixes #50
```
in the original comment on the first line.  Put any additional comments on subsequent lines.

**Comment by josarnold** [comment]
@yorkshire-pudding 
It is possible, that I was wrong about the VimeoVanisher.php andt the problem only lies in the EmbeddedVideoVanisher.php. As You can see in the VimeoVanisher.php – the paths are captured like documented here: https://gist.github.com/anjan011/1fcecdc236594e6d700f
I did not find the time to check the whole thing again but it may be, that the VimeoVanisher.php is OK an only the EmbeddedVideoVanisher.php caused the problem.

**Comment by josarnold** [comment]
Now i found the time to check it again – and yes, it is only the EmbeddedVideoVanisher.php as described in #55. The default size fallback is an optional idea.

**Comment by olafgrabienski** [comment]
@josarnold Thanks for the update! I've applied the `EmbeddedVideoVanisher.php` part of PR https://github.com/backdrop-contrib/gdpr_cookies/pull/55 to my test site, and it fixes the issue for me, be it with and without the size fallback.

**Comment by yorkshire-pudding** [comment]
@olafgrabienski @josarnold - so is this tested and ready functionally? I don't use Vimeo so can't really test.
@josarnold  - please revert the spacing changes you made as they don't relate to the issue. Backdrop's coding standards were addressed in #33 and so no coding style adjustments need to be done on existing code.

**Comment by josarnold** [comment]
@yorkshire-pudding – I updated the patch, but it appears to look more confusing now. Shall I dump it and do another request? I could do another testing session as well.

**Comment by olafgrabienski** [comment]
> so is this tested and ready functionally?

@yorkshire-pudding I think so, as mentioned in https://github.com/backdrop-contrib/gdpr_cookies/issues/50#issuecomment-4223957461. And I can test again when @josarnold has committed the suggestions in the PR.

**Comment by yorkshire-pudding** [comment]
@josarnold - I'll hang on until you are able to fix the entire issue as I'm not sure of the benefit of a partially fixed issue.
@olafgrabienski - FYI
